image: cloudfoundry/warden-ci

env:
  - GOROOT=/usr/local/go
  - PATH=$GOROOT/bin:$PATH
  - GOPATH=/tmp/build
  - PATH=/tmp/build/bin:$PATH
  - REPO_DIR=$GOPATH/src/github.com/cloudfoundry-incubator/warden-linux

script: |
  mkdir -p $(dirname $REPO_DIR)
  mv warden-linux $REPO_DIR

  cd $REPO_DIR
  ./scripts/drone-test {{ .Args }}
